### ISSUE TITLE
Evaluate feasibility of Shiny interface

### ISSUE THREAD

**Issue by montilab** [montilab/Hydra#23]
Organize Hydra output in a Shiny module
See where the server (which needs to be Linux) could run. SCC? Elsewhere?

**Comment by gusef** [comment]
Found a way to generate standalone plot.ly interactive plots. To generate them automatically they have to be embedded into an Rmd which has to be complied in turn. So it's definitely doable, I just need to find the time to wrap it into the pipeline..

**Comment by montilab** [comment]
I thought plot.ly <http://plot.ly/> was a commercial product (Vinay told me so), that’d be great if you proved me wrong!

--ste

**Comment by gusef** [comment]
plot.ly tries to push their online service and tries to force you to put the output online, which has the same drawback as shiney, you need to host them somewhere.

You can however just use the free version in R studio and then save the plots which generates a stand-alone html that has the required java script embedded. The same can be done when embedding the plot in a rmd file.

To do this automatically in the pipeline I need a wrapper to compile the .rmd to a .md and then into a .html. RStudio has a nice button for that, but I will write a script that does the same. If only the day had 36 hours.. ;)
