### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by ericreed** [montilab/Hydra#30]
I'm trying to build the conda package using the conda package guide and keep getting an error.  Right now I'm just trying to run conda build hydra-1.0.0 using the original git source (no changes).  I'm running the code in the help page (subbing in my own directories of course).  I've printed the output below, the final line has the error.  Any help it welcome.

Removing old build directory
Removing old work directory
BUILD START: hydra-1.0.0-monti_2
Fetching package metadata: ........

WARNING: conda-build appears to be out of date. You have version 1.11.0 but the
latest version is 2.0.7. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications: .......................
The following NEW packages will be INSTALLED:

    biopython:        1.65-np19py27_0
    cairo:            1.12.18-6
    dbus:             1.10.10-0
    expat:            2.1.0-0
    fontconfig:       2.11.1-6
    freetype:         2.5.5-1
    funcsigs:         1.0.2-py27_0
    glib:             2.43.0-1
    gmp:              5.1.2-2
    gst-plugins-base: 1.8.0-0
    gstreamer:        1.8.0-0
    harfbuzz:         0.9.39-1
    icu:              54.1-0
    isl:              0.12.2-0
    libffi:           3.2.1-0
    libpng:           1.6.17-0
    libxml2:          2.9.2-0
    matplotlib:       1.4.3-np19py27_2
    mkl:              11.3.3-0
    mock:             2.0.0-py27_0
    nose:             1.3.7-py27_1
    numpy:            1.9.3-py27_3
    openssl:          1.0.2j-0
    pango:            1.39.0-1
    pbr:              1.10.0-py27_0
    pip:              8.1.2-py27_0
    pixman:           0.32.6-0
    py2cairo:         1.10.0-py27_2
    pyparsing:        2.0.3-py27_0
    pyqt:             4.11.4-py27_4
    pysam:            0.6-py27_0
    python:           2.7.12-1
    python-dateutil:  2.5.3-py27_0
    pytz:             2016.7-py27_0
    qt:               4.8.7-4
    readline:         6.2-2
    setuptools:       27.2.0-py27_0
    sip:              4.18-py27_0
    six:              1.10.0-py27_0
    sqlite:           3.13.0-0
    tk:               8.5.18-0
    wheel:            0.29.0-py27_0
    zlib:             1.2.8-3

Linking packages ...
[      COMPLETE      ] |##################################################################################################################| 100%
dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id
Removing old work directory
Password:
checkout: u'v1.0.0'
Initialized empty Git repository in /restricted/projectnb/montilab-p/personal/eric/condaWS/conda_build_space/work/.git/
Note: checking out 'v1.0.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 1041d98... Changed version number of Hydra
==> git log -n1 <==

commit 1041d98440c8056747de549064fc1e643768de80
Author: montilab <montilab@bu.edu>
Date:   Tue Jun 16 14:52:02 2015 -0400

    Changed version number of Hydra

==> git describe --tags --dirty <==

v1.0.0

==> git status <==

# Not currently on any branch.
nothing to commit (working directory clean)

Package: hydra-1.0.0-monti_2
source tree in: /restricted/projectnb/montilab-p/personal/eric/condaWS/conda_build_space/work
+ /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin/python setup.py install
running install
running bdist_egg
running egg_info
creating hydra.egg-info
writing requirements to hydra.egg-info/requires.txt
writing hydra.egg-info/PKG-INFO
writing top-level names to hydra.egg-info/top_level.txt
writing dependency_links to hydra.egg-info/dependency_links.txt
writing entry points to hydra.egg-info/entry_points.txt
writing manifest file 'hydra.egg-info/SOURCES.txt'
reading manifest file 'hydra.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'AUTHORS.rst'
warning: no files found matching '*' under directory 'tests'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'hydra.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/hydra_pkg
copying hydra_pkg/pipeline.py -> build/lib/hydra_pkg
copying hydra_pkg/tophat.py -> build/lib/hydra_pkg
copying hydra_pkg/featureCount.py -> build/lib/hydra_pkg
copying hydra_pkg/__init__.py -> build/lib/hydra_pkg
copying hydra_pkg/qsub_module.py -> build/lib/hydra_pkg
copying hydra_pkg/star.py -> build/lib/hydra_pkg
copying hydra_pkg/cufflinks.py -> build/lib/hydra_pkg
copying hydra_pkg/bamqc.py -> build/lib/hydra_pkg
copying hydra_pkg/helper.py -> build/lib/hydra_pkg
copying hydra_pkg/r_scripts.py -> build/lib/hydra_pkg
copying hydra_pkg/cutadapt.py -> build/lib/hydra_pkg
copying hydra_pkg/fastqc.py -> build/lib/hydra_pkg
copying hydra_pkg/matched_pairs.py -> build/lib/hydra_pkg
copying hydra_pkg/module_helper.py -> build/lib/hydra_pkg
copying hydra_pkg/single_cpu_module.py -> build/lib/hydra_pkg
copying hydra_pkg/logs.py -> build/lib/hydra_pkg
copying hydra_pkg/htseq.py -> build/lib/hydra_pkg
creating build/lib/hydra_pkg/Icons
copying hydra_pkg/Icons/error.png -> build/lib/hydra_pkg/Icons
copying hydra_pkg/Icons/fastqc_icon.png -> build/lib/hydra_pkg/Icons
copying hydra_pkg/Icons/tick.png -> build/lib/hydra_pkg/Icons
copying hydra_pkg/Icons/warning.png -> build/lib/hydra_pkg/Icons
creating build/lib/hydra_pkg/r_scripts
copying hydra_pkg/r_scripts/createRawCountESet.R -> build/lib/hydra_pkg/r_scripts
copying hydra_pkg/r_scripts/cufflinks_pca.R -> build/lib/hydra_pkg/r_scripts
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/pipeline.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/tophat.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/featureCount.py -> build/bdist.linux-x86_64/egg/hydra_pkg
creating build/bdist.linux-x86_64/egg/hydra_pkg/Icons
copying build/lib/hydra_pkg/Icons/tick.png -> build/bdist.linux-x86_64/egg/hydra_pkg/Icons
copying build/lib/hydra_pkg/Icons/error.png -> build/bdist.linux-x86_64/egg/hydra_pkg/Icons
copying build/lib/hydra_pkg/Icons/warning.png -> build/bdist.linux-x86_64/egg/hydra_pkg/Icons
copying build/lib/hydra_pkg/Icons/fastqc_icon.png -> build/bdist.linux-x86_64/egg/hydra_pkg/Icons
copying build/lib/hydra_pkg/__init__.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/qsub_module.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/star.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/cufflinks.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/bamqc.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/helper.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/r_scripts.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/cutadapt.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/fastqc.py -> build/bdist.linux-x86_64/egg/hydra_pkg
creating build/bdist.linux-x86_64/egg/hydra_pkg/r_scripts
copying build/lib/hydra_pkg/r_scripts/cufflinks_pca.R -> build/bdist.linux-x86_64/egg/hydra_pkg/r_scripts
copying build/lib/hydra_pkg/r_scripts/createRawCountESet.R -> build/bdist.linux-x86_64/egg/hydra_pkg/r_scripts
copying build/lib/hydra_pkg/matched_pairs.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/module_helper.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/single_cpu_module.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/logs.py -> build/bdist.linux-x86_64/egg/hydra_pkg
copying build/lib/hydra_pkg/htseq.py -> build/bdist.linux-x86_64/egg/hydra_pkg
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/pipeline.py to pipeline.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/tophat.py to tophat.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/featureCount.py to featureCount.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/qsub_module.py to qsub_module.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/star.py to star.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/cufflinks.py to cufflinks.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/bamqc.py to bamqc.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/helper.py to helper.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/r_scripts.py to r_scripts.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/cutadapt.py to cutadapt.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/fastqc.py to fastqc.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/matched_pairs.py to matched_pairs.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/module_helper.py to module_helper.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/single_cpu_module.py to single_cpu_module.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/logs.py to logs.pyc
byte-compiling build/bdist.linux-x86_64/egg/hydra_pkg/htseq.py to htseq.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying scripts/hydra-rnaseq -> build/scripts-2.7
copying and adjusting scripts/paired_ends_intersect.py -> build/scripts-2.7
copying scripts/run_bamqc.py -> build/scripts-2.7
changing mode of build/scripts-2.7/hydra-rnaseq from 644 to 755
changing mode of build/scripts-2.7/paired_ends_intersect.py from 644 to 755
changing mode of build/scripts-2.7/run_bamqc.py from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/paired_ends_intersect.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/hydra-rnaseq -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/run_bamqc.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/paired_ends_intersect.py to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/hydra-rnaseq to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/run_bamqc.py to 755
copying hydra.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hydra.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hydra.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hydra.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hydra.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hydra.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hydra.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/hydra-2.0.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing hydra-2.0.0-py2.7.egg
creating /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/hydra-2.0.0-py2.7.egg
Extracting hydra-2.0.0-py2.7.egg to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Adding hydra 2.0.0 to easy-install.pth file
Installing paired_ends_intersect.py script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing hydra-rnaseq script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_bamqc.py script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_featureCount script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_matched_pairs script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_star script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_cufflinks script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_fastqc script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_tophat script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_htseq script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_cutadapt script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing run_bamqc script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin

Installed /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages/hydra-2.0.0-py2.7.egg
Processing dependencies for hydra==2.0.0
Searching for biopython==1.65
Best match: biopython 1.65
Adding biopython 1.65 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for pysam==0.6
Best match: pysam 0.6
Adding pysam 0.6 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for matplotlib==1.4.3
Best match: matplotlib 1.4.3
Adding matplotlib 1.4.3 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for numpy==1.9.3
Best match: numpy 1.9.3
Adding numpy 1.9.3 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for mock==2.0.0
Best match: mock 2.0.0
Adding mock 2.0.0 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for nose==1.3.7
Best match: nose 1.3.7
Adding nose 1.3.7 to easy-install.pth file
Installing nosetests script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin
Installing nosetests-2.7 script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for pyparsing==2.0.3
Best match: pyparsing 2.0.3
Adding pyparsing 2.0.3 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for pytz==2016.7
Best match: pytz 2016.7
Adding pytz 2016.7 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for python-dateutil==2.5.3
Best match: python-dateutil 2.5.3
Adding python-dateutil 2.5.3 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for funcsigs==1.0.2
Best match: funcsigs 1.0.2
Adding funcsigs 1.0.2 to easy-install.pth file

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Searching for pbr==1.10.0
Best match: pbr 1.10.0
Adding pbr 1.10.0 to easy-install.pth file
Installing pbr script to /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/bin

Using /usr3/graduate/reeder/.conda/envs/_build_placehold_placehold_placehold_placehold/lib/python2.7/site-packages
Finished processing dependencies for hydra==2.0.0
compiling .pyc files...
number of files: 66
Detected hard-coded path in text file bin/hydra-rnaseq
Detected hard-coded path in text file bin/nosetests-2.7
Detected hard-coded path in text file bin/paired_ends_intersect.py
Detected hard-coded path in text file bin/run_bamqc
Detected hard-coded path in text file bin/run_bamqc.py
Detected hard-coded path in text file bin/run_cufflinks
Detected hard-coded path in text file bin/run_cutadapt
Detected hard-coded path in text file bin/run_fastqc
Detected hard-coded path in text file bin/run_featureCount
Detected hard-coded path in text file bin/run_htseq
Detected hard-coded path in text file bin/run_matched_pairs
Detected hard-coded path in text file bin/run_star
Detected hard-coded path in text file bin/run_tophat
Detected hard-coded path in text file lib/python2.7/site-packages/hydra-2.0.0-py2.7.egg/EGG-INFO/scripts/paired_ends_intersect.py
BUILD END: hydra-1.0.0-monti_2
TEST START: hydra-1.0.0-monti_2
Fetching package metadata: ........

WARNING: conda-build appears to be out of date. You have version 1.11.0 but the
latest version is 2.0.7. Run

conda update -n root conda-build

to get the latest version.

Solving package specifications:
Error: Could not find some dependencies for hydra 1.0.0 monti_2: bowtie2 2.2.2

**Comment by gusef** [comment]
Is your hydra environment still activated? Make sure it is not. And when I built it this morning I used the conda version that you get when you 'module load anaconda2'

**Comment by ericreed** [comment]
No the environment is not activated.  I tried again using anaconda2.  Now I'm getting a different error (below),

Solving package specifications: .
Error:  Packages/dependencies missing in current linux-64 channels:
  - hydra 1.0.0 monti_2 -> cufflinks 2.2.0
  - hydra 1.0.0 monti_2 -> samtools 0.1.19
  - hydra 1.0.0 monti_2 -> star 2.4.1d
  - hydra 1.0.0 monti_2 -> r-base 3.3.1
  - hydra 1.0.0 monti_2 -> htseq 0.6.1p1
  - hydra 1.0.0 monti_2 -> pysam 0.7.7
  - hydra 1.0.0 monti_2 -> tophat 2.0.13
  - hydra 1.0.0 monti_2 -> bowtie2 2.2.2
  - hydra 1.0.0 monti_2 -> fastqc 0.11.2
  - hydra 1.0.0 monti_2 -> cutadapt 1.8.1
  - hydra 1.0.0 monti_2 -> subread 1.4.6
  - samtools 0.1.19
  - bowtie2 2.2.2
  - cufflinks 2.2.0
  - cutadapt 1.8.1
  - fastqc 0.11.2
  - htseq 0.6.1p1
  - pysam 0.7.7
  - r-base 3.3.1
  - subread 1.4.6
  - tophat 2.0.13
  - star 2.4.1d

**Comment by gusef** [comment]
Just installed it, worked without any issues. Here are the exact lines of code I used:

```
qrsh -P montilab-p
module load anaconda2
cd /restricted/projectnb/montilab-p/projects/pipeline_dev/Hydra/conda_packages
WORKSPACE=/restricted/projectnb/montilab-p/projects/pipeline_dev
export CONDA_BLD_PATH=$WORKSPACE/conda_build_space
conda build hydra-1.0.0

```

Since we use the same conda version and hydra is installed from the github repo it is probably your recipe? 

The only thing that I haven't gotten to work yet is setting the standard anaconda_env, which currently points to the home directory. This is where the additional packages are downloaded. Let me know if you find a fix for that. Tired of deleting that directory every single time I rebuild.

**Comment by gusef** [comment]
Hey Eric, did you resolve this issue? Can you please close open issues once they are resolved?
