### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by vkartha** [montilab/Hydra#32]
Get the following error on scc:
Error: Could not find some dependencies for hydra: ncurses >=5.9.*

**Comment by bioliyezhang** [comment]
The error I got is similar:
Error: Could not find some dependencies for hydra: ncurses >=5.9.*, cufflinks 2.2.1

**Comment by montilab** [comment]
Are you using Eric’s version of the pipeline?

https://github.com/montilab/Hydra/tree/v1.0.2 <https://github.com/montilab/Hydra/tree/v1.0.2>

**Comment by bioliyezhang** [comment]
No, I guess I am still seeing the old one, I did not see the v1.0.2 page. I will try the newer version later on.

**Comment by montilab** [comment]
Yeah, sorry, I think Eric hasn’t committed it yet as the official version, but will do it soon

—ste
