### ISSUE TITLE
Updated Version of Hydra (v1.0.2)

### ISSUE THREAD

**Issue by ericreed** [montilab/Hydra#33]
Hi All,

This isn't a proper issue, but I have an updated version of Hydra.  I've added it to tag, v1.0.2.   These changes include the addition of bowtie2 to align short reads, as well as updates to the versions of different packages to run Hydra.  The packages in this version get downloaded from other anaconda.org accounts, such that I'm only hosting the Hydra package on my personal anaconda.org account.  There are new instructions for downloading on the v1.0.2 github page, but I haven't updated any of the developers' instructions. 

Check it out, try and break it, all that fun stuff.

**Comment by bioliyezhang** [comment]
Error with v1.0.2:

Fetching package metadata ...........
NoPackagesFoundError: Package missing in current linux-64 channels:
  - cufflinks 2.2.1*

**Comment by montilab** [comment]
You should pester Eric :)

—ste
